version: "0.5"

# Load environment variables from .env file
env_file: .env

processes:
  nats-server:
    command: task nats-server:start
    readiness_probe:
      exec:
        command: task nats-cli:rtt
      initial_delay_seconds: 1
      period_seconds: 2

  main:
    command: task main:start
    depends_on:
      nats-server:
        condition: process_healthy
    environment:
      - TERM=xterm-256color
    # No health check - GUI app, runs until closed

  # Optional: telemetry watcher (uncomment to auto-subscribe)
  # telemetry:
  #   command: task nats-cli:sub
  #   depends_on:
  #     nats-server:
  #       condition: process_healthy

  # Voxel-fun 3D visualizer
  voxel:
    command: task voxel:start
    depends_on:
      nats-server:
        condition: process_healthy
    readiness_probe:
      http_get:
        host: localhost
        port: $VOXEL_PORT
        path: /
      initial_delay_seconds: 3
      period_seconds: 5

  # Narun HTTP/gRPC gateway to NATS
  narun:
    command: task narun:start
    depends_on:
      nats-server:
        condition: process_healthy
    readiness_probe:
      http_get:
        host: localhost
        port: $NARUN_METRICS_PORT
        path: /metrics
      initial_delay_seconds: 2
      period_seconds: 5
