version: '3'

# Load .env first, then .env.local overrides (for secrets)
dotenv: ['.env', '.env.local']

includes:
  voxel:
    taskfile: ./systems/voxel/Taskfile.voxel.yml
    vars:
      ROOT_DIR: '{{.PWD}}'
  nats-server:
    taskfile: ./systems/nats-server/Taskfile.nats-server.yml
    vars:
      ROOT_DIR: '{{.PWD}}'
  nats-cli:
    taskfile: ./systems/nats-cli/Taskfile.nats-cli.yml
    vars:
      ROOT_DIR: '{{.PWD}}'
  narun:
    taskfile: ./systems/narun/Taskfile.narun.yml
    vars:
      ROOT_DIR: '{{.PWD}}'
  pc:
    taskfile: ./systems/pc/Taskfile.pc.yml
    vars:
      ROOT_DIR: '{{.PWD}}'
  nats2sse:
    taskfile: ./systems/nats2sse/Taskfile.nats2sse.yml
    vars:
      ROOT_DIR: '{{.PWD}}'
  selfhostmap:
    taskfile: ./systems/selfhostmap/Taskfile.selfhostmap.yml
    vars:
      ROOT_DIR: '{{.PWD}}'

vars:
  # globals ( that all included stuff also uses)
  BIN_DIR: .bin
  DATA_DIR: .data
  SRC_DIR: .src

tasks:
  default:
    desc: Run the simulator with GUI
    cmds:
      - task: main:start

  debug:
    desc: Print root vars and env
    cmds:
      - echo "=== Root Vars ==="
      - echo "BIN_DIR={{.BIN_DIR}}"
      - echo "DATA_DIR={{.DATA_DIR}}"
      - echo "SRC_DIR={{.SRC_DIR}}"
      - echo ""
      - echo "=== Env (.env) ==="
      - echo "NATS_PORT=$NATS_PORT"
      - echo "NATS_URL=$NATS_URL"
      - echo "VOXEL_PORT=$VOXEL_PORT"
      - echo "NARUN_PORT=$NARUN_PORT"
      - echo "NARUN_METRICS_PORT=$NARUN_METRICS_PORT"
      - echo "PC_PORT=$PC_PORT"
      - echo "NATS2SSE_PORT=$NATS2SSE_PORT"
      - echo "SELFHOSTMAP_PORT=$SELFHOSTMAP_PORT"
    silent: true

  debug:all:
    desc: Print debug info for all systems
    cmds:
      - task: debug
      - task: debug:main
      - task: nats-server:debug:self
      - task: nats-cli:debug:self
      - task: narun:debug:self
      - task: voxel:debug:self
      - task: pc:debug:self
      - task: nats2sse:debug:self
      - task: selfhostmap:debug:self

  # Deps tasks
  deps:install:
    desc: Install all external dependencies (process-compose, nats-server, nats-cli, voxel)
    deps:
      - pc:deps:install
      - nats-server:deps:install
      - nats-cli:deps:install
      - voxel:deps:install

  deps:clean:
    desc: Remove all installed dependencies
    cmds:
      - rm -rf {{.BIN_DIR}}

  # Main simulator tasks
  debug:main:
    desc: Print main simulator info
    cmds:
      - 'echo "=== Main Simulator ==="'
      - 'echo "Binary: go run ."'
      - 'echo "NATS_URL=$NATS_URL"'
      - 'echo ""'
      - 'echo "Flags:"'
      - 'echo "  -headless     Run without GUI"'
      - 'echo "  -nats-url     NATS server URL"'
      - 'echo "  -steps=N      Fixed update count (headless)"'
      - 'echo "  -duration=5s  Run duration (headless)"'
      - 'echo "  -ups=120      Updates per second"'
    silent: true

  main:start:
    desc: Start simulator with NATS enabled (uses NATS_URL from .env)
    cmds:
      - go run .

  main:start:headless:
    desc: Start simulator headless with NATS (uses NATS_URL from .env)
    cmds:
      - go run . -headless

  main:start:standalone:
    desc: Start simulator with GUI (no NATS)
    cmds:
      - go run .

  main:build:
    desc: Build the simulator binary
    cmds:
      - mkdir -p {{.BIN_DIR}}
      - go build -o {{.BIN_DIR}}/drone-simulator .

  main:test:
    desc: Run all tests
    cmds:
      - go test ./...

  main:test:cover:
    desc: Run tests with coverage
    cmds:
      - go test -cover ./...

  main:test:verbose:
    desc: Run tests with verbose output
    cmds:
      - go test -v ./...

  main:vet:
    desc: Run static analysis
    cmds:
      - go vet ./...

  main:fmt:
    desc: Format all Go code
    cmds:
      - go fmt ./...

  main:lint:
    desc: Run fmt and vet
    cmds:
      - task: main:fmt
      - task: main:vet

  main:tidy:
    desc: Download and tidy dependencies
    cmds:
      - go mod tidy

  main:clean:
    desc: Remove build artifacts
    cmds:
      - rm -f {{.BIN_DIR}}/drone-simulator

  # CI tasks
  ci:
    desc: Run full CI pipeline locally
    cmds:
      - task: main:tidy
      - task: main:fmt
      - task: main:vet
      - task: main:test
