version: '3'

dotenv: ['.env']

includes:
  voxel:
    taskfile: ./systems/voxel/Taskfile.voxel.yml
    vars:
      ROOT_DIR: '{{.PWD}}'
  nats:
    taskfile: ./systems/nats/Taskfile.nats.yml
    vars:
      ROOT_DIR: '{{.PWD}}'
  narun:
    taskfile: ./systems/narun/Taskfile.narun.yml
    vars:
      ROOT_DIR: '{{.PWD}}'
  pc:
    taskfile: ./systems/pc/Taskfile.pc.yml
    vars:
      ROOT_DIR: '{{.PWD}}'

vars:
  # globals
  BIN_DIR: .bin
  DATA_DIR: .data

tasks:
  default:
    desc: Run the simulator with GUI
    cmds:
      - task: sim:run

  debug:
    desc: Print all vars and env for debugging
    cmds:
      - echo "=== Vars ==="
      - echo "BIN_DIR={{.BIN_DIR}}"
      - echo "DATA_DIR={{.DATA_DIR}}"
      - echo ""
      - echo "=== Env (.env) ==="
      - echo "NATS_PORT=$NATS_PORT"
      - echo "NATS_URL=$NATS_URL"
    silent: true

  # Go tasks
  go:build:
    desc: Build the simulator binary
    cmds:
      - mkdir -p {{.BIN_DIR}}
      - go build -o {{.BIN_DIR}}/drone-simulator .

  go:test:
    desc: Run all tests
    cmds:
      - go test ./...

  go:test:cover:
    desc: Run tests with coverage
    cmds:
      - go test -cover ./...

  go:test:verbose:
    desc: Run tests with verbose output
    cmds:
      - go test -v ./...

  go:vet:
    desc: Run static analysis
    cmds:
      - go vet ./...

  go:fmt:
    desc: Format all Go code
    cmds:
      - go fmt ./...

  go:lint:
    desc: Run fmt and vet
    cmds:
      - task: go:fmt
      - task: go:vet

  go:tidy:
    desc: Download and tidy dependencies
    cmds:
      - go mod tidy

  go:clean:
    desc: Remove build artifacts
    cmds:
      - rm -f {{.BIN_DIR}}/drone-simulator

  # Deps tasks
  deps:install:
    desc: Install all external dependencies (process-compose, nats, voxel)
    deps:
      - pc:deps:install
      - nats:deps:install
      - voxel:deps:install

  deps:clean:
    desc: Remove all installed dependencies
    cmds:
      - rm -rf {{.BIN_DIR}}

  # Simulator tasks (called by process-compose)
  sim:run:
    desc: Run simulator with NATS enabled (called by process-compose)
    cmds:
      - go run . -nats-url=$NATS_URL

  sim:run:headless:
    desc: Run simulator headless with NATS (called by process-compose)
    cmds:
      - go run . -nats-url=$NATS_URL -headless

  sim:run:standalone:
    desc: Run simulator with GUI (no NATS)
    cmds:
      - go run .

  # CI tasks
  ci:
    desc: Run full CI pipeline locally
    cmds:
      - task: go:tidy
      - task: go:fmt
      - task: go:vet
      - task: go:test
